language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - redis

install:
  - |
    echo "no" | pecl install -f redis
  - |
    wget https://github.com/swoole/swoole-src/archive/v4.4.17.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure && make -j$(nproc) && make install && cd - && rm -rf swoole
    echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - |
    wget -O bin/php-cs-fixer "https://cs.symfony.com/download/php-cs-fixer-v2.phar"
    chmod +x bin/php-cs-fixer

before_script:
  - phpenv config-rm xdebug.ini
  - bin/php-cs-fixer -V
  - composer config -g process-timeout 900 && composer update
  - composer require --dev phpstan/phpstan

script:
  - composer check-cs
  - composer test
#  - php bin/swoft dinfo:env
